# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 30

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 7

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - "next ⛳"
  
# Label to use when marking an issue as stale
staleLabel: wontfix 🚫

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This has been automatically marked as stale because it has not had  
  recent activity. It will be closed if no further activity occurs. 
  Feel free to reopen whenever you want. Thank you for your contributions.
  
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
