module.exports = {
  prefix: 'vtmn-',
  purge: ['src/stories/**/*.mdx'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      mobile: '0px',
      tablet: '600px',
      'small-desktop': '896px',
      'medium-desktop': '1200px',
      'large-desktop': '1800px',
    },
    colors: {
      black: 'var(--vtmn-color_black)',
      'brand-digital': 'var(--vtmn-color_brand-digital)',
      'brand-digital-dark-1': 'var(--vtmn-color_brand-digital-dark-1)',
      'brand-digital-dark-2': 'var(--vtmn-color_brand-digital-dark-2)',
      'brand-digital-light-1': 'var(--vtmn-color_brand-digital-light-1)',
      'brand-digital-light-2': 'var(--vtmn-color_brand-digital-light-2)',
      'brand-digital-light-3': 'var(--vtmn-color_brand-digital-light-3)',
      green: 'var(--vtmn-color_green)',
      'green-dark-1': 'var(--vtmn-color_green-dark-1)',
      'green-dark-2': 'var(--vtmn-color_green-dark-2)',
      'green-light-1': 'var(--vtmn-color_green-light-1)',
      'green-light-2': 'var(--vtmn-color_green-light-2)',
      'green-light-3 ': 'var(--vtmn-color_green-light-3)',
      grey: 'var(--vtmn-color_grey)',
      'grey-dark-1': 'var(--vtmn-color_grey-dark-1)',
      'grey-dark-2': 'var(--vtmn-color_grey-dark-2)',
      'grey-dark-3': 'var(--vtmn-color_grey-dark-3)',
      'grey-light-1': 'var(--vtmn-color_grey-light-1)',
      'grey-light-2': 'var(--vtmn-color_grey-light-2)',
      'grey-light-3': 'var(--vtmn-color_grey-light-3)',
      'grey-light-4': 'var(--vtmn-color_grey-light-4)',
      orange: 'var(--vtmn-color_orange)',
      'color_orange-light-1': 'var(--vtmn-color_orange-light-1)',
      'color_orange-light-2': 'var(--vtmn-color_orange-light-2)',
      red: 'var(--vtmn-color_red)',
      'red-light-1': 'var(--vtmn-color_red-light-1)',
      'red-light-2': 'var(--vtmn-color_red-light-2)',
      white: 'var(--vtmn-color_white)',
      yellow: 'var(--vtmn-color_yellow)',
      'yellow-light-1': 'var(--vtmn-color_yellow-light-1)',
      'yellow-light-2': 'var(--vtmn-color_yellow-light-2)',
      success: 'var(--vtmn-color_success)',
      info: 'var(--vtmn-color_info)',
      warning: 'var(--vtmn-color_warning)',
      danger: 'var(--vtmn-color_danger)',
    },
    spacing: {
      '01': '4px',
      '02': '8px',
      '03': '12px',
      '04': '16px',
      '05': '24px',
      '06': '32px',
      '07': '40px',
      '08': '48px',
      '09': '56px',
      10: '64px',
    },
    fontFamily: {
      display: ['Roboto Condensed', 'system-ui', '-apple-system'],
      body: ['Roboto', 'system-ui', '-apple-system'],
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
