module.exports = {
  prefix: 'vtmn-',
  purge: ['src/stories/**/*.mdx'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      mobile: '0px',
      tablet: '600px',
      'small-desktop': '896px',
      'medium-desktop': '1200px',
      'large-desktop': '1800px',
    },
    colors: {
      black: '#001018',
      'brand-digital': '#007dbc',
      'brand-digital-dark-1': '#00689d',
      'brand-digital-dark-2': '#00537d',
      'brand-digital-light-1': '#7ebee0',
      'brand-digital-light-2': '#bedeef',
      'brand-digital-light-3': '#e7f3f9',
      green: '#02be8a',
      'green-dark-1': '#029e73',
      'green-dark-2': '#017f5c',
      'green-light-1': '#7cdfc4',
      'green-light-2': '#beefe2',
      'green-light-3': '#e4f9f3',
      grey: '#687787',
      'grey-dark-1': '#4e5d6b',
      'grey-dark-2': '#344450',
      'grey-dark-3': '#1a2a34',
      'grey-light-1': '#b3bac3',
      'grey-light-2': '#d9dde1',
      'grey-light-3': '#eff1f3',
      'grey-light-4': '#f7f8f9',
      orange: '#fe5800',
      'orange-light-1': '#feab7b',
      'orange-light-2': '#fed5bd',
      red: '#ee000c',
      'red-light-1': '#ed8b8f',
      'red-light-2': '#f5c7c9',
      white: '#ffffff',
      yellow: '#ffea28',
      'yellow-light-1': '#fff58d',
      'yellow-light-2': '#fffbc7',
      success: '#23a942',
      info: '#007dbc',
      warning: '#ff600a',
      danger: '#e32c26',
    },
    spacing: {
      '01': '4px',
      '02': '8px',
      '03': '12px',
      '04': '16px',
      '05': '24px',
      '06': '32px',
      '07': '40px',
      '08': '48px',
      '09': '56px',
      10: '64px',
    },
    fontFamily: {
      display: ['Roboto Condensed', 'system-ui', '-apple-system'],
      body: ['Roboto', 'system-ui', '-apple-system'],
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
